### ISSUE TITLE
Consider using XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wallpaperMaker#11]
Here: https://github.com/WnndGws/wallpaperMaker/blob/fb291bd02d32062b14193de70cc1439965d005a5/get_calendar_events.py#L25-L27

check XDG_CONFIG_HOME
otherwise $HOME/.config

**Comment by WnndGws** [comment]
Think I addressed in it [ad3c60d](https://github.com/WnndGws/Agendrum/commit/ad3c60db36fc807e8f2f084f0fd66430417573db) but havent tested as got sidetracked with the need for a better oauth flow

**Comment by ammgws** [comment]
On phone so assuming it's done
