### ISSUE TITLE
DRY: config location code basically duplicated

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wallpaperMaker#12]
[DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

https://github.com/WnndGws/wallpaperMaker/blob/fb291bd02d32062b14193de70cc1439965d005a5/get_calendar_events.py#L41-L42

and

https://github.com/WnndGws/wallpaperMaker/blob/fb291bd02d32062b14193de70cc1439965d005a5/get_calendar_events.py#L25-L27

Since have a global variable, might as well make it reusable?

**Comment by WnndGws** [comment]
Addressed in general code cleanup
