### ISSUE TITLE
Not using env shebang

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wallpaperMaker#14]
https://github.com/WnndGws/wallpaperMaker/blob/fb291bd02d32062b14193de70cc1439965d005a5/manipulate_image.py#L1

https://github.com/WnndGws/wallpaperMaker/blob/fb291bd02d32062b14193de70cc1439965d005a5/get_calendar_events.py#L1

https://github.com/WnndGws/wallpaperMaker/blob/fb291bd02d32062b14193de70cc1439965d005a5/download_wallpaper_image.py#L1

Use `#!/usr/bin/env python` instead. Also I think only the entry script (manipulate) needs it since the other ones are not run directly.

**Comment by WnndGws** [comment]
Why? Python2 wont run it

**Comment by ammgws** [comment]
Doesn't have anything to do with python2

What if python isn't installed at /bin/python3 or /usr/bin/python3?
Using the env one means it will find the first python in the user's $PATH.
Also trying to use virtualenvs won't work if not changed.

**Comment by ammgws** [comment]
Preemptive closure since this will be fixed by you tonight

**Comment by WnndGws** [comment]
Fixed
