### ISSUE TITLE
Add screenshot to README

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wallpaperMaker#18]

**Comment by WnndGws** [comment]
Screenshot of what? An example output?

**Comment by ammgws** [comment]
Yes, to see how the overlay looks. Expecting comic sans

**Comment by WnndGws** [comment]
Addressed in commit [166e455](https://github.com/WnndGws/Agendrum/commit/166e4557dbdf40efdc8764743b016665d97f952e)
