### ISSUE TITLE
Change name to something other than "wallpaper maker"?

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wallpaperMaker#2]
On top of being generic, the program itself is very specific: downloads from Bing, queries Google Calendar.

What about "Bing! ~~Condom~~ wallpaper"? (Not a real suggestion)

**Comment by WnndGws** [comment]
Any suggestions? Something that alludes to the schedule, since might want to have other sources in the future?

"agenda-wallpaper"?

**Comment by ammgws** [comment]
Badabingbadawallpaper

All I can think about is Seinfeld

**Comment by WnndGws** [comment]
Dont want to focus on the bing preview. I think the agenda part is the nice part

**Comment by WnndGws** [comment]
Proposed name:

Agendrum: a portmanteau of "Agendum" (Latin for “which ought to be done”, referring to the agenda text), and "Murum" (Latin for "wall")

**Comment by ammgws** [comment]
Ga head

**Comment by ammgws** [comment]
I had a peek into the future and found this was solved at 3AM.
