### ISSUE TITLE
Entry point is weird

### ISSUE THREAD

**Issue by ammgws** [WnndGws/wallpaperMaker#3]
Weird that the entry point to the program is "manipulate image", sounds like some internal function rather than a command an end user would run. Shouldn't the main entry point basically be the name of the program?

**Comment by WnndGws** [comment]
I agree. This and #2 will be addressed for v0.2

**Comment by WnndGws** [comment]
Addressed by adding `program.py`. Will rename when think of a name.

**Comment by WnndGws** [comment]
Addressed in [v0.2](https://github.com/WnndGws/Agendrum/releases/tag/v0.2) release.

Reopen if not satisfied
